# action.yml
name: "Hello-World"
description: "Greet someone and record the time"
inputs:
  changed-files: # id of input
    description: "List of files that were changed"
    required: true
    default: "[]"
outputs:
  time: # id of output
    description: "Time of completion"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.changed-files }}
