set term ^ ;

ALTER TRIGGER DWELLAUTOOPTIONS_CHANGED INACTIVE^
ALTER TRIGGER DWELLING_CHANGED INACTIVE^
ALTER TRIGGER DWELLING_DELREFUND INACTIVE^
ALTER TRIGGER APP_DWELLING_CHANGED INACTIVE^
ALTER TRIGGER DWELLING_CHANGED_FORMS INACTIVE^
ALTER TRIGGER DWELLING_BEFORE_UPDATE INACTIVE^
ALTER TRIGGER DWELLING_AU_SET_GLASS_BI_LIMITS INACTIVE^
commit^

UPDATE DWELLING 
   SET SQUARE_FOOTAGE_LENGTH = 0,
       SQUARE_FOOTAGE_WIDTH = 0^
commit^

ALTER TRIGGER DWELLAUTOOPTIONS_CHANGED ACTIVE^
ALTER TRIGGER DWELLING_CHANGED ACTIVE^
ALTER TRIGGER DWELLING_DELREFUND ACTIVE^
ALTER TRIGGER APP_DWELLING_CHANGED ACTIVE^
ALTER TRIGGER DWELLING_CHANGED_FORMS ACTIVE^
ALTER TRIGGER DWELLING_BEFORE_UPDATE ACTIVE^
ALTER TRIGGER DWELLING_AU_SET_GLASS_BI_LIMITS ACTIVE^
commit^

set term ; ^

insert into applied_scripts (name, description, script_date)
     values ('210519AO01', 'FUE-1967 - dwelling square footage dimensions init', '2021-May-19');
