on: push
# pull_request:
#   types: [opened, reopened]

jobs:
  job2:
    name: get-changed-files
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step2.outputs.changedFiles }}
    steps:
      - id: step1
        uses: jitterbit/get-changed-files@v1
        with:
          format: "json"
          # not sure if this step is needed
      - id: step2
        run: |
          echo "::set-output name=changedFiles::${{ steps.step1.outputs.added_modified }}"

  job3:
    name: check-applied-scripts
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run applied scripts check
        shell: bash
        # uses: xiappi/test-actions/actions/applied_scripts_action@main
        run: |
          chmod +x ./entrypoint.sh
          ./entrypoint.sh "${{needs.job2.outputs.output1}}"
