on: push
# pull_request:
#   types: [opened, reopened]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: xiappi/test-actions/action1@main
        with:
          who-to-greet: "Mona the Octocat"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  job2:
    name: get-changed-files
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step2.outputs.changedFiles }}
    steps:
      - id: step1
        uses: jitterbit/get-changed-files@v1
        with:
          format: "json"
          # not sure if this step is needed
      - id: step2
        run: |
          echo "::set-output name=changedFiles::${{ steps.step1.outputs.added_modified }}"

  job3:
    name: check-applied-scripts
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - id: step1
        uses: xiappi/test-actions/actions/applied_scripts_action@main
        with:
          changed-files: "${{needs.job2.outputs.output1}}"
